INSERT INTO CONVERSOR (COD_CONVERSOR, MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO, ESTADO) VALUES (1,'DOLARES', 'SOLES', 3.67, 0);
INSERT INTO CONVERSOR (COD_CONVERSOR, MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO, ESTADO) VALUES (2,'SOLES', 'DOLARES', 0.26, 1);
INSERT INTO CONVERSOR (COD_CONVERSOR, MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO, ESTADO) VALUES (3,'DOLARES', 'SOLES', 3.70, 0);
INSERT INTO CONVERSOR (COD_CONVERSOR, MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO, ESTADO) VALUES (4,'DOLARES', 'SOLES', 3.84, 1);