DROP TABLE IF EXISTS CONVERSOR;  
CREATE TABLE CONVERSOR (  
	COD_CONVERSOR INT PRIMARY KEY,  
	MONEDA_ORIGEN VARCHAR(50) NOT NULL,
	MONEDA_DESTINO VARCHAR(50) NOT NULL,
	TIPO_CAMBIO NUMERIC(9,2) NOT NULL,
	ESTADO INT NOT NULL  
);  